Updated GorevIkiFragment.kt,fragment_gorev_iki.xml and GorevIkiViewMo…
mendess12/mobillium-staj-task3 pull request #2
Opened 2023-04-10 11:22 UTC by mendess12

…del.kt

2023-04-17 08:49 UTC, ckavuzlu requested changes

2023-04-17 08:49 UTC, ckavuzlu commented on app/src/main/java/com/example/mobilliumtask3/ikincigorev/GorevIkiFragment.kt
> +           selectNumberObserveLiveData()
observe function'ları 1 kere çağırman yeterli her clickte çağırmayabilirsin.

2023-04-17 08:49 UTC, ckavuzlu commented on app/src/main/java/com/example/mobilliumtask3/ikincigorev/GorevIkiViewModel.kt
> +            selectNumberLiveData.postValue("win")
win ve try again bir durumun 2 state'i o yüzden Enum class içine alabilirsin

2023-04-17 08:49 UTC, ckavuzlu commented on app/src/main/java/com/example/mobilliumtask3/ikincigorev/GorevIkiFragment.kt
> +                binding.clearButton.setOnClickListener {
clicklistener da event observe ediyor bu yüzden 1 kere tanımlaman yeterli

2023-04-28 12:10 UTC, kemaldeliceli requested changes

2023-04-28 12:10 UTC, kemaldeliceli commented on app/src/main/java/com/example/mobilliumtask3/MainFragment.kt
>  }
classın başında değerlerden önce ve sonra bir boşluk daha iyi olur

2023-04-28 12:10 UTC, kemaldeliceli commented on app/src/main/java/com/example/mobilliumtask3/ikincigorev/GorevIkiFragment.kt
> +        println(viewModel.randomNumber)
Log kullanılabilir

2023-06-19 05:10 UTC, merged